#!/bin/bash
n=$1

case $n in
  1)
    proj='moves-like-final.rhythmr'
    ;;
  2)
    proj='brubeck-64-66.rhythmr'
    ;;
  *)
    echo "??" $n
    exit 1
esac

cp farm-performance-histories/$proj/history $proj/history
g demo $proj
