#!/bin/bash
root=`stack path --local-install-root`
exe=$root/bin/rhythmr
app=Rhythmr.app
app_template=$app-template

# if [ -e "$app" ]; then
#   echo $app already exists
#   exit 1
# fi

rm -r Rhythmr.app

cp -r distribution/app-template/$app_template ./$app
cp $exe $app/Contents/MacOS/rhythmr
./distribution/generate-icns
