#!/usr/bin/env bash

## No bash script should be considered releasable until it has this! ##
# Exit on use of an uninitialized variable
set -o nounset
# Exit if any statement returns a non-true return value (non-zero).
set -o errexit

log=$HOME/rhythmr/boo

exec 1>$log
exec 2>&1

## Put your script below. Don't take out the part above.
echo args $*
date
pwd
echo 0 $0
thisScript=$0
echo $thisScript
contents=`dirname $(dirname $(dirname $thisScript))`
exe=$contents/MacOS/rhythmr
doc=$1
echo exe $exe
ls $exe
file $exe
echo doc $doc
ls $doc
file "$doc"
$exe aff $doc
echo bye
